version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    container_name: client-container
    ports:
      - '80:80'
    volumes:
      - app:/client

volumes:
  mongodb-data:
  app:
